In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


## single dimensional array

In [2]:
import numpy as np

In [3]:
mylist = [2,4,5]
n = np.array(mylist)

In [4]:
n

array([2, 4, 5])

In [5]:
type(mylist)


list

In [6]:
type(n)

numpy.ndarray

In [7]:
# OR

m = np.array([2,4,5])
m

array([2, 4, 5])

## Multi Dimensional array

In [8]:
list_of_lists = np.array([[2,3,4], [5,6,7],[8,9,0]])
list_of_lists

array([[2, 3, 4],
       [5, 6, 7],
       [8, 9, 0]])

In [9]:
list_of_lists.shape

(3, 3)

# Arange Function

In [10]:
np.arange(0,20,5)

array([ 0,  5, 10, 15])

In [11]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

# Zeros, ones, Eye Function

In [21]:
zero = np.zeros(30)
zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
zeros = np.zeros([3,3])
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
ones = np.ones([3,3])
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
#eye will go the diagonal
eye = np.eye(10)
eye

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [22]:
eyes = np.eye(2)
eyes

array([[1., 0.],
       [0., 1.]])

# Reshape

In [23]:
mn = np.arange(0,50)
mn

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [25]:
len(mn)

50

In [26]:
mn.reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

# Linspace

In [28]:
o = np.linspace(0,7,10)
o

array([0.        , 0.77777778, 1.55555556, 2.33333333, 3.11111111,
       3.88888889, 4.66666667, 5.44444444, 6.22222222, 7.        ])

In [29]:
v = np.linspace(0,3,5)
v

array([0.  , 0.75, 1.5 , 2.25, 3.  ])

# Resize

In [30]:
o.resize(5,2)
o

array([[0.        , 0.77777778],
       [1.55555556, 2.33333333],
       [3.11111111, 3.88888889],
       [4.66666667, 5.44444444],
       [6.22222222, 7.        ]])

# Generating some Random value

In [31]:
np.random.rand(3,2)

array([[0.22534919, 0.70206691],
       [0.83846027, 0.24137239],
       [0.27627184, 0.14087714]])

In [32]:
np.random.randn(3,2)

array([[ 0.1765661 ,  0.56390015],
       [ 0.74045814,  2.18007566],
       [-2.16235844, -1.01058992]])

In [33]:
np.random.randint(4,15,10)

array([10,  5, 12,  4, 10,  4,  7,  9,  4,  8])

# Broadcasting

In [36]:
mn[mn >25]=25
mn

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 25, 25, 25, 25, 25, 25, 25, 25,
       25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25])

# Dataframe

In [43]:
import pandas as pd

data = pd.read_csv('games.csv')

In [44]:
data

id                type  \
0       12333           boardgame   
1      120677           boardgame   
2      102794           boardgame   
3       25613           boardgame   
4        3076           boardgame   
...       ...                 ...   
81307  184441  boardgameexpansion   
81308  184442           boardgame   
81309  184443           boardgame   
81310  184449           boardgame   
81311  184451           boardgame   

                                                    name  yearpublished  \
0                                      Twilight Struggle         2005.0   
1                                          Terra Mystica         2012.0   
2                              Caverna: The Cave Farmers         2013.0   
3              Through the Ages: A Story of Civilization         2006.0   
4                                            Puerto Rico         2002.0   
...                                                  ...            ...   
81307                               Micro Rome: Aegyptus         2015.0   
81308  Trivial Pursuit: Marvel Cinematic Universe  Da...         2013.0   
81309                                          BEARanoia         2015.0   
81310                                            Freight         2015.0   
81311                                  Bingo Animal Kids         2010.0   

       minplayers  maxplayers  playingtime  minplaytime  maxplaytime  minage  \
0             2.0         2.0        180.0        180.0        180.0    13.0   
1             2.0         5.0        150.0         60.0        150.0    12.0   
2             1.0         7.0        210.0         30.0        210.0    12.0   
3             2.0         4.0        240.0        240.0        240.0    12.0   
4             2.0         5.0        150.0         90.0        150.0    12.0   
...           ...         ...          ...          ...          ...     ...   
81307         1.0         1.0          0.0         30.0          0.0    10.0   
81308         2.0         0.0          0.0          0.0          0.0    12.0   
81309         2.0        15.0          1.0          1.0          1.0     0.0   
81310         2.0         4.0         60.0         30.0         60.0     8.0   
81311         1.0         6.0         10.0         10.0         10.0     2.0   

       users_rated  average_rating  bayes_average_rating  total_owners  \
0            20113         8.33774               8.22186         26647   
1            14383         8.28798               8.14232         16519   
2             9262         8.28994               8.06886         12230   
3            13294         8.20407               8.05804         14343   
4            39883         8.14261               8.04524         44362   
...            ...             ...                   ...           ...   
81307            0         0.00000               0.00000             0   
81308            0         0.00000               0.00000             0   
81309            0         0.00000               0.00000             0   
81310            0         0.00000               0.00000             0   
81311            0         0.00000               0.00000             0   

       total_traders  total_wanters  total_wishers  total_comments  \
0                372           1219           5865            5347   
1                132           1586           6277            2526   
2                 99           1476           5600            1700   
3                362           1084           5075            3378   
4                795            861           5414            9173   
...              ...            ...            ...             ...   
81307              0              0              0               0   
81308              0              0              0               0   
81309              0              0              0               0   
81310              0              0              0               0   
81311              0              0          

In [47]:
data.head()

id       type                                       name  \
0   12333  boardgame                          Twilight Struggle   
1  120677  boardgame                              Terra Mystica   
2  102794  boardgame                  Caverna: The Cave Farmers   
3   25613  boardgame  Through the Ages: A Story of Civilization   
4    3076  boardgame                                Puerto Rico   

   yearpublished  minplayers  maxplayers  playingtime  minplaytime  \
0         2005.0         2.0         2.0        180.0        180.0   
1         2012.0         2.0         5.0        150.0         60.0   
2         2013.0         1.0         7.0        210.0         30.0   
3         2006.0         2.0         4.0        240.0        240.0   
4         2002.0         2.0         5.0        150.0         90.0   

   maxplaytime  minage  users_rated  average_rating  bayes_average_rating  \
0        180.0    13.0        20113         8.33774               8.22186   
1        150.0    12.0        14383         8.28798               8.14232   
2        210.0    12.0         9262         8.28994               8.06886   
3        240.0    12.0        13294         8.20407               8.05804   
4        150.0    12.0        39883         8.14261               8.04524   

   total_owners  total_traders  total_wanters  total_wishers  total_comments  \
0         26647            372           1219           5865            5347   
1         16519            132           1586           6277            2526   
2         12230             99           1476           5600            1700   
3         14343            362           1084           5075            3378   
4         44362            795            861           5414            9173   

   total_weights  average_weight  
0           2562          3.4785  
1           1423          3.8939  
2            777          3.7761  
3           1642          4.1590  
4           5213          3.2943

In [48]:
df = data.copy()

In [49]:
df

id                type  \
0       12333           boardgame   
1      120677           boardgame   
2      102794           boardgame   
3       25613           boardgame   
4        3076           boardgame   
...       ...                 ...   
81307  184441  boardgameexpansion   
81308  184442           boardgame   
81309  184443           boardgame   
81310  184449           boardgame   
81311  184451           boardgame   

                                                    name  yearpublished  \
0                                      Twilight Struggle         2005.0   
1                                          Terra Mystica         2012.0   
2                              Caverna: The Cave Farmers         2013.0   
3              Through the Ages: A Story of Civilization         2006.0   
4                                            Puerto Rico         2002.0   
...                                                  ...            ...   
81307                               Micro Rome: Aegyptus         2015.0   
81308  Trivial Pursuit: Marvel Cinematic Universe  Da...         2013.0   
81309                                          BEARanoia         2015.0   
81310                                            Freight         2015.0   
81311                                  Bingo Animal Kids         2010.0   

       minplayers  maxplayers  playingtime  minplaytime  maxplaytime  minage  \
0             2.0         2.0        180.0        180.0        180.0    13.0   
1             2.0         5.0        150.0         60.0        150.0    12.0   
2             1.0         7.0        210.0         30.0        210.0    12.0   
3             2.0         4.0        240.0        240.0        240.0    12.0   
4             2.0         5.0        150.0         90.0        150.0    12.0   
...           ...         ...          ...          ...          ...     ...   
81307         1.0         1.0          0.0         30.0          0.0    10.0   
81308         2.0         0.0          0.0          0.0          0.0    12.0   
81309         2.0        15.0          1.0          1.0          1.0     0.0   
81310         2.0         4.0         60.0         30.0         60.0     8.0   
81311         1.0         6.0         10.0         10.0         10.0     2.0   

       users_rated  average_rating  bayes_average_rating  total_owners  \
0            20113         8.33774               8.22186         26647   
1            14383         8.28798               8.14232         16519   
2             9262         8.28994               8.06886         12230   
3            13294         8.20407               8.05804         14343   
4            39883         8.14261               8.04524         44362   
...            ...             ...                   ...           ...   
81307            0         0.00000               0.00000             0   
81308            0         0.00000               0.00000             0   
81309            0         0.00000               0.00000             0   
81310            0         0.00000               0.00000             0   
81311            0         0.00000               0.00000             0   

       total_traders  total_wanters  total_wishers  total_comments  \
0                372           1219           5865            5347   
1                132           1586           6277            2526   
2                 99           1476           5600            1700   
3                362           1084           5075            3378   
4                795            861           5414            9173   
...              ...            ...            ...             ...   
81307              0              0              0               0   
81308              0              0              0               0   
81309              0              0              0               0   
81310              0              0              0               0   
81311              0              0          

In [51]:
df['type']

0                 boardgame
1                 boardgame
2                 boardgame
3                 boardgame
4                 boardgame
                ...        
81307    boardgameexpansion
81308             boardgame
81309             boardgame
81310             boardgame
81311             boardgame
Name: type, Length: 81312, dtype: object